# Generated by Django 3.2.11 on 2022-01-09 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bookstore.author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bookstore.book')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_bookstore.author')),
            ],
        ),
    ]
